In [1]:
import numpy as np

## Creating a array

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b=np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [4]:
c=np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [6]:
np.linspace(1,20,8)

array([ 1.        ,  3.71428571,  6.42857143,  9.14285714, 11.85714286,
       14.57142857, 17.28571429, 20.        ])

In [9]:
np.full((3,2),(4,5))# 2 by 2 matrix filled with 7

array([[4, 5],
       [4, 5],
       [4, 5]])

In [12]:
np.eye(4)# creates and identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.random((2,2))# creates floting array

array([[0.73863399, 0.5075495 ],
       [0.08837267, 0.99868171]])

In [20]:
np.random.randint(100)#generates a number in between 0-100

35

In [21]:
np.random.randint(100,size=(3,5))#creates a 3 by 5 array in between 0-100

array([[61,  3, 58, 91, 69],
       [97, 34, 16,  9, 36],
       [25, 67, 42,  8,  0]])

In [23]:
np.random.rand(3,5)

array([[0.99101073, 0.14466899, 0.11421216, 0.81551714, 0.86586834],
       [0.02538906, 0.10802001, 0.98989565, 0.85156303, 0.35712133],
       [0.18688776, 0.15350597, 0.98537238, 0.19671889, 0.03829215]])

## Arithmetic operation

In [25]:
a=np.random.randint(50,size=(3,5))
a

array([[48,  1, 48, 20,  1],
       [44, 28, 12,  7, 11],
       [35,  5, 28, 31, 25]])

In [28]:
b=np.random.randint(50,size=(3,5))
b

array([[ 5, 12, 22, 32, 20],
       [41, 48, 27, 12,  4],
       [27, 22, 44,  3, 37]])

In [29]:
a+b

array([[53, 13, 70, 52, 21],
       [85, 76, 39, 19, 15],
       [62, 27, 72, 34, 62]])

In [30]:
a-b

array([[ 43, -11,  26, -12, -19],
       [  3, -20, -15,  -5,   7],
       [  8, -17, -16,  28, -12]])

In [31]:
a*b

array([[ 240,   12, 1056,  640,   20],
       [1804, 1344,  324,   84,   44],
       [ 945,  110, 1232,   93,  925]])

In [32]:
a//b

array([[ 9,  0,  2,  0,  0],
       [ 1,  0,  0,  0,  2],
       [ 1,  0,  0, 10,  0]])

In [33]:
a**b

array([[  254803968,           1,           0,           0,           1],
       [          0,           0,           0,   956385313,       14641],
       [ -766269925, -2094601527,           0,       29791,   235612665]])

In [34]:
c = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
d = np.array([1.0, 2.0, 3.0])
c+d

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

## Comparision Opertor

In [35]:
a=np.random.randint(50,size=(3,5))
a

array([[43,  9,  2, 46, 16],
       [ 5, 36, 17, 22, 25],
       [37, 17, 29, 22,  9]])

In [36]:
b=np.random.randint(50,size=(3,5))
b

array([[ 2, 44, 12,  4, 28],
       [28,  5, 10,  4, 22],
       [44,  1, 31, 22, 28]])

In [37]:
a==b

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [38]:
a>b

array([[ True, False, False,  True, False],
       [False,  True,  True,  True,  True],
       [False,  True, False, False, False]])

In [39]:
a<b

array([[False,  True,  True, False,  True],
       [ True, False, False, False, False],
       [ True, False,  True, False,  True]])

In [40]:
a>2

array([[ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Aggregate Function

In [41]:
a=np.random.randint(50,size=(3,5))
a

array([[11, 23, 24, 22, 20],
       [29, 38,  8, 44, 37],
       [36, 41, 38, 37, 11]])

In [42]:
a.sum()

419

In [43]:
a.min()

8

In [44]:
a.max()

44

In [46]:
np.median(a)

29.0

In [47]:
np.std(a)

11.462790042374307

In [48]:
np.sqrt(b)

array([[1.41421356, 6.63324958, 3.46410162, 2.        , 5.29150262],
       [5.29150262, 2.23606798, 3.16227766, 2.        , 4.69041576],
       [6.63324958, 1.        , 5.56776436, 4.69041576, 5.29150262]])

In [49]:
np.var(b)

202.93333333333334

## Copying an Arrays

In [50]:
view_data=b.view()
view_data

array([[ 2, 44, 12,  4, 28],
       [28,  5, 10,  4, 22],
       [44,  1, 31, 22, 28]])

In [51]:
copy_a=a.copy()
copy_a

array([[11, 23, 24, 22, 20],
       [29, 38,  8, 44, 37],
       [36, 41, 38, 37, 11]])